### ISSUE TITLE
Filters for specific  files

### ISSUE THREAD

**Issue by L4yer** [Mte90/DL-Telegram-by-file-attachment#5]
Hello and first let me say thanks for this. I was wondering if it is possible to use filters to match certain files/titles. Could you explain how i could use this to monitor a channel and auto download all files titled "free.pdf" 

I presume i could just set this to run on cron or something.

Thanks

**Comment by Mte90** [comment]
I was using a cron, if you check the https://github.com/Mte90/DL-Telegram-by-file-attachment/blob/master/config-sample.ini there is the filter so you can configure it as you want
